//! Does the Rust port of Kronos produce the numbers the reference implementation does?
//!
//! **Ignored by default**, because it needs 115 MB of weights that are not in the repository.
//! The input and the expected output are upstream's own regression fixture
//! (`tests/data/` in shiyu-coder/Kronos, MIT), generated by the reference PyTorch code with
//! greedy decoding at the exact model revisions `localai::catalogue` pins. Upstream's own test
//! accepts a relative error of 1e-5 against these files, and so does this one.
//!
//! ```bash
//! KRONOS_WEIGHTS_DIR=/path/to/weights \
//!   cargo test --release --test kronos_parity -- --ignored --nocapture
//! ```
//!
//! The directory needs `kronos-small.safetensors` and `kronos-tokenizer-base.safetensors`.
//! `--release` matters: this is a transformer on the CPU, and a debug build takes minutes.

use std::path::PathBuf;

use brew_terminal_lib::localai::kronos::{predict, stamp, Kronos, Sampling, Tokenizer, FEATURES};

const REL_TOLERANCE: f32 = 1e-5;
const MAX_CONTEXT: usize = 512;

fn fixture(name: &str) -> Vec<(i64, [f32; FEATURES])> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/kronos")
        .join(name);
    std::fs::read_to_string(path)
        .expect("fixture")
        .lines()
        .skip(1)
        .map(|line| {
            let mut cells = line.split(',');
            let time = chrono::NaiveDateTime::parse_from_str(
                cells.next().expect("timestamp"),
                "%Y-%m-%d %H:%M:%S",
            )
            .expect("timestamp format")
            .and_utc()
            .timestamp();
            let mut row = [0.0; FEATURES];
            for value in row.iter_mut() {
                *value = cells.next().expect("six columns").parse().expect("number");
            }
            (time, row)
        })
        .collect()
}

fn matches_upstream(context_len: usize) {
    let dir = PathBuf::from(
        std::env::var("KRONOS_WEIGHTS_DIR").expect("set KRONOS_WEIGHTS_DIR to the weights folder"),
    );
    let tokenizer = Tokenizer::load(&dir.join("kronos-tokenizer-base.safetensors")).unwrap();
    let model = Kronos::load(&dir.join("kronos-small.safetensors")).unwrap();

    let input = fixture("regression_input.csv");
    let expected = fixture(&format!("regression_output_{context_len}.csv"));

    let candles: Vec<_> = input[..context_len].iter().map(|(_, row)| *row).collect();
    let stamps: Vec<_> = input[..context_len]
        .iter()
        .map(|(t, _)| stamp(*t))
        .collect();
    let ahead: Vec<_> = expected.iter().map(|(t, _)| stamp(*t)).collect();

    let started = std::time::Instant::now();
    let paths = predict(
        &tokenizer,
        &model,
        &candles,
        &stamps,
        &ahead,
        MAX_CONTEXT,
        Sampling::Greedy,
    );
    println!("context {context_len}: {:?}", started.elapsed());

    let mut worst = 0.0f32;
    for (got, (_, want)) in paths[0].iter().zip(&expected) {
        for f in 0..FEATURES {
            worst = worst.max((got[f] - want[f]).abs() / (want[f].abs() + 1e-9));
        }
    }
    println!("context {context_len}: worst relative difference {worst:e}");

    assert_eq!(paths[0].len(), expected.len());
    assert!(
        worst <= REL_TOLERANCE,
        "differs from the reference implementation by {worst:e}"
    );
}

/// Context and output fit the window together, so this exercises the cached, incremental path —
/// the one the app uses.
#[test]
#[ignore = "needs the Kronos weights; see the module comment"]
fn matches_the_reference_implementation_within_the_window() {
    matches_upstream(256);
}

/// The context already fills the window, so every step slides it and recomputes from scratch.
#[test]
#[ignore = "needs the Kronos weights; see the module comment"]
fn matches_the_reference_implementation_when_the_window_slides() {
    matches_upstream(512);
}

/// The shape of request the app actually makes: sampled, several paths, well inside the window.
/// There is no reference output for a sampled run — a different random stream gives different
/// paths — so this checks what can be checked: the output is usable, the paths genuinely
/// differ, and the same seed gives the same answer.
#[test]
#[ignore = "needs the Kronos weights; see the module comment"]
fn a_sampled_run_is_usable_varied_and_repeatable() {
    let dir = PathBuf::from(std::env::var("KRONOS_WEIGHTS_DIR").expect("KRONOS_WEIGHTS_DIR"));
    let tokenizer = Tokenizer::load(&dir.join("kronos-tokenizer-base.safetensors")).unwrap();
    let model = Kronos::load(&dir.join("kronos-small.safetensors")).unwrap();

    let input = fixture("regression_input.csv");
    let candles: Vec<_> = input[..180].iter().map(|(_, row)| *row).collect();
    let stamps: Vec<_> = input[..180].iter().map(|(t, _)| stamp(*t)).collect();
    let ahead: Vec<_> = input[180..204].iter().map(|(t, _)| stamp(*t)).collect();
    let sampling = Sampling::Nucleus {
        temperature: 1.0,
        top_p: 0.9,
        paths: 20,
        seed: 7,
    };

    let run = || {
        predict(
            &tokenizer,
            &model,
            &candles,
            &stamps,
            &ahead,
            MAX_CONTEXT,
            sampling,
        )
    };

    let started = std::time::Instant::now();
    let paths = run();
    println!("180 candles, 24 ahead, 20 paths: {:?}", started.elapsed());

    assert_eq!(paths.len(), 20);
    assert!(paths.iter().all(|path| path.len() == 24));
    assert!(paths.iter().flatten().flatten().all(|v| v.is_finite()));
    assert!(
        paths.iter().any(|path| path != &paths[0]),
        "every path was identical"
    );
    assert_eq!(paths, run(), "the same seed gave a different answer");

    // The context closes near 11.2; a path that wandered to 3 or 40 would mean the decode or
    // the de-normalisation was wrong, not that the model was pessimistic.
    let last_close = candles[179][3];
    assert!(paths
        .iter()
        .flatten()
        .all(|candle| (candle[3] / last_close - 1.0).abs() < 0.2));
}

/// The reference fixture only exercises one path at a time, but the app steps twenty paths
/// through the model together. This ties the two: with the nucleus shrunk to a single token,
/// sampling can only ever pick the most likely one, so every path of a batched run must be
/// exactly the greedy path that the fixture has already verified.
#[test]
#[ignore = "needs the Kronos weights; see the module comment"]
fn paths_stepped_together_each_match_the_path_stepped_alone() {
    let dir = PathBuf::from(std::env::var("KRONOS_WEIGHTS_DIR").expect("KRONOS_WEIGHTS_DIR"));
    let tokenizer = Tokenizer::load(&dir.join("kronos-tokenizer-base.safetensors")).unwrap();
    let model = Kronos::load(&dir.join("kronos-small.safetensors")).unwrap();

    let input = fixture("regression_input.csv");
    let candles: Vec<_> = input[..256].iter().map(|(_, row)| *row).collect();
    let stamps: Vec<_> = input[..256].iter().map(|(t, _)| stamp(*t)).collect();
    let ahead: Vec<_> = input[256..264].iter().map(|(t, _)| stamp(*t)).collect();

    let run = |sampling| {
        predict(
            &tokenizer,
            &model,
            &candles,
            &stamps,
            &ahead,
            MAX_CONTEXT,
            sampling,
        )
    };
    let alone = run(Sampling::Greedy);
    let together = run(Sampling::Nucleus {
        temperature: 1.0,
        top_p: 0.0,
        paths: 3,
        seed: 1,
    });

    assert_eq!(together.len(), 3);
    for path in &together {
        assert_eq!(path, &alone[0]);
    }
}

/// The whole feature, as the app runs it: acknowledgement, weights on disk, candles from a
/// provider, the model, the summary. The provider is the mock one, so the candles are
/// synthetic and the envelope says so — what is real here is everything downstream of them.
#[tokio::test]
#[ignore = "needs the Kronos weights; see the module comment"]
async fn the_service_runs_the_model_end_to_end() {
    use brew_terminal_lib::models::EnvelopeSource;
    use brew_terminal_lib::services::{kronos, settings};
    use brew_terminal_lib::state::AppState;

    let weights = PathBuf::from(std::env::var("KRONOS_WEIGHTS_DIR").expect("KRONOS_WEIGHTS_DIR"));
    let dir = tempfile::tempdir().unwrap();
    let state = AppState::bootstrap(dir.path().to_path_buf()).unwrap();
    {
        // Only the mock provider, as `app_flow.rs` does: no network, and a fixed input.
        let conn = state.pool.get().unwrap();
        for live in ["coingecko", "finnhub"] {
            brew_terminal_lib::db::repo_providers::set_enabled(&conn, live, false).unwrap();
        }
        brew_terminal_lib::db::repo_providers::set_enabled(&conn, "mock", true).unwrap();
    }

    let installed = brew_terminal_lib::localai::store::kronos_dir(&state.data_dir);
    std::fs::create_dir_all(&installed).unwrap();
    for file in [
        "kronos-tokenizer-base.safetensors",
        "kronos-small.safetensors",
    ] {
        std::fs::copy(weights.join(file), installed.join(file)).unwrap();
    }
    assert!(kronos::status(&state).installed);

    settings::set_preference(&state, "kronosAcknowledged".into(), "true".into())
        .await
        .unwrap();

    let envelope = kronos::project(&state, "crypto:cg:bitcoin".into())
        .await
        .unwrap();
    assert_eq!(envelope.meta.source, EnvelopeSource::Mock);

    let projection = envelope.data.expect("the fixture has a year of candles");
    println!(
        "{} candles in, {} out, {} paths, {} ms",
        projection.context_candles,
        projection.points.len(),
        projection.paths,
        projection.elapsed_ms
    );

    // The fixture is daily, so this is the ten-candle daily horizon, on consecutive days —
    // crypto trades at weekends, and nothing should have been skipped.
    assert_eq!(projection.interval_secs, 86_400);
    assert_eq!(projection.points.len(), 10);
    assert_eq!(projection.paths, 20);
    assert!(!projection.has_volume);
    let last = projection.history.last().unwrap();
    assert_eq!(projection.points[0].time, last.time + 86_400);
    assert!(projection
        .points
        .windows(2)
        .all(|pair| pair[1].time - pair[0].time == 86_400));

    for point in &projection.points {
        assert!(point.low <= point.mean && point.mean <= point.high);
        assert!(point.low > 0.0);
        // A projection an order of magnitude from the last close would be a units bug.
        assert!((point.mean / last.close - 1.0).abs() < 0.5);
    }
    // Twenty sampled paths that never disagree would mean sampling is not happening.
    assert!(projection.points.iter().any(|p| p.high > p.low));
}
