import { DisclaimerNote } from '@/components/status/DisclaimerNote';
import { Icon } from '@/components/ui/Icon';
import type { AiMessage } from '@/types/domain';
import { scanResponse } from './guardrails';
import styles from './MessageList.module.css';

interface MessageListProps {
  messages: AiMessage[];
  /** Rendered as a pending assistant turn while a request is in flight. */
  pending: boolean;
}

/**
 * The transcript.
 *
 * Every assistant turn is rendered as escaped plain text — no Markdown, no HTML, no links made
 * clickable. Model output is untrusted input in exactly the way provider output is, and
 * `local/no-raw-html` bans the alternative outright. See THREAT_MODEL.md §3.
 *
 * Layer 3 of the guardrails lives here: a response matching the banned vocabulary gets a
 * caution above it, quoting what matched. The answer is still shown in full — hiding it would
 * leave the user unable to judge whether their own model is behaving, which is the one thing
 * they most need to see. See AI_POLICY.md §5.
 */
export function MessageList({ messages, pending }: MessageListProps) {
  if (messages.length === 0 && !pending) {
    return (
      <div className={styles.empty}>
        <p className={styles.emptyTitle}>Nothing asked yet</p>
        <p className={styles.emptyBody}>
          Ask what something means, how an instrument works, or what a metric actually measures. Ask
          what to buy and it will decline, then answer the question underneath.
        </p>
      </div>
    );
  }

  return (
    <ol className={styles.list} role="list">
      {messages.map((message) => {
        const isAssistant = message.role === 'assistant';
        const cautions = isAssistant ? scanResponse(message.content) : [];

        return (
          <li key={message.id} className={isAssistant ? styles.assistant : styles.user}>
            <p className={styles.role}>{isAssistant ? 'Model' : 'You'}</p>

            {cautions.length > 0 ? (
              <div className={styles.caution} role="note">
                <Icon name="warning" size={14} />
                <span>
                  This answer contains advice-shaped language — {formatCautions(cautions)}. It is
                  shown unchanged so you can judge it yourself.
                </span>
              </div>
            ) : null}

            <p className={styles.content}>{message.content}</p>

            {isAssistant ? (
              <DisclaimerNote variant="inline" context="Generated by the model you configured." />
            ) : null}
          </li>
        );
      })}

      {pending ? (
        <li className={styles.assistant} aria-live="polite">
          <p className={styles.role}>Model</p>
          <p className={styles.pending}>Waiting for a response. A local model can take a while.</p>
        </li>
      ) : null}
    </ol>
  );
}

/** Quotes what matched, so the caution names the problem instead of gesturing at it. */
function formatCautions(cautions: string[]): string {
  const quoted = cautions.map((c) => `“${c}”`);
  if (quoted.length === 1) return quoted[0] as string;
  return `${quoted.slice(0, -1).join(', ')} and ${quoted[quoted.length - 1] as string}`;
}
